### ISSUE TITLE
Environment variables scoped under 's3' are not working

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/config#2]
e.g.: `defaults.json`

```
{
  "s3": {
    "bucket": "bucke-name"
  }
}
```

If I try to set it via `S3_BUCKET` doesn't work.

**Comment by gvilarino** [comment]
Any insights as to why?

**Comment by gvilarino** [comment]
I've confirme this doesn't work also with a value like `url2png`. The symptom feels like "if there's a number in the name, I won't work".

**Comment by gvilarino** [comment]
This probably seems like it: https://github.com/blakeembrey/no-case/pull/7

@mjlescano can you please release a new version of `dos-config` with `change-case@3.0.0`?

Make sure our tests by @franciclo pass before releasing, and add a test for a setting like `s3endpoint` or anything with a number in it.

**Comment by gvilarino** [comment]
:+1:
